### ISSUE TITLE
大佬云函数出错了可以帮我看一下吗

### ISSUE THREAD

**Issue by 1987980421** [Chorer/WoZaiXiaoYuanPuncher-cloudFunction#1]
![图片](https://user-images.githubusercontent.com/85055405/130895699-ff299f69-6066-4f8e-9903-1191633b0716.png)
qq：8827974

**Comment by Chorer** [comment]
@1987980421 从报错信息来看是 `leancloud.Query('Info').first()` 这一句有问题。你是不是没有在 leanCloud 控制台那里创建 Info 这个 class？

**Comment by pzsu** [comment]
> @1987980421 从报错信息来看是 `leancloud.Query('Info').first()` 这一句有问题。你是不是没有在 leanCloud 控制台那里创建 Info 这个 class？

我也是这个报错，Info创建了的，新建列名为jwsession,没有值，一直不知道什么原因，就是测试失败

**Comment by Chorer** [comment]
@1987980421 在 leanCloud 的 Info class 那里新添加一行，有出现 objectId 就行了

**Comment by pzsu** [comment]
> @1987980421 在 leanCloud 的 Info class 那里新添加一行，有出现 objectId 就行了

感谢，终于成功了，不过那个readme文件讲解的步骤那里产生了歧义，产生理解错误，所以没有新建行。
还有一个问题，就是如果在家怎么填那个config文件，那个填的是城市和学校，在家的话怎么填

**Comment by Chorer** [comment]
> > @1987980421 在 leanCloud 的 Info class 那里新添加一行，有出现 objectId 就行了
> 
> 感谢，终于成功了，不过那个readme文件讲解的步骤那里产生了歧义，产生理解错误，所以没有新建行。
> 还有一个问题，就是如果在家怎么填那个config文件，那个填的是城市和学校，在家的话怎么填

city改为自己现在所在的城市，school改为自己家的具体地址，数据库里面的 hasAddress 改为 false，这样会重新计算一次地址，测试完去数据库看看里面的地址信息对不对

**Comment by pzsu** [comment]
> > > @1987980421 在 leanCloud 的 Info class 那里新添加一行，有出现 objectId 就行了
> > 
> > 
> > 感谢，终于成功了，不过那个readme文件讲解的步骤那里产生了歧义，产生理解错误，所以没有新建行。
> > 还有一个问题，就是如果在家怎么填那个config文件，那个填的是城市和学校，在家的话怎么填
> 
> city改为自己现在所在的城市，school改为自己家的具体地址，数据库里面的 hasAddress 改为 false，这样会重新计算一次地址，测试完去数据库看看里面的地址信息对不对

在index里吗，咋看地址信息对不对

**Comment by Chorer** [comment]
> > > > @1987980421 在 leanCloud 的 Info class 那里新添加一行，有出现 objectId 就行了
> > > 
> > > 
> > > 感谢，终于成功了，不过那个readme文件讲解的步骤那里产生了歧义，产生理解错误，所以没有新建行。
> > > 还有一个问题，就是如果在家怎么填那个config文件，那个填的是城市和学校，在家的话怎么填
> > 
> > 
> > city改为自己现在所在的城市，school改为自己家的具体地址，数据库里面的 hasAddress 改为 false，这样会重新计算一次地址，测试完去数据库看看里面的地址信息对不对
> 
> 在index里吗，咋看地址信息对不对

index.py 是源代码文件，不要动它。city 和 school 在 config.json 改，hasAddress 在 leancloud 的数据库改，改完测试一下，数据库会更新地址信息，你检查看看街道和城镇和自己现在的地址是否对应就可以了。
