### ISSUE TITLE
(麻烦可以看一下吗/(ㄒoㄒ)/~~) LeanCloudError: [101] Object not found","statusCode

### ISSUE THREAD

**Issue by shiziru** [Chorer/WoZaiXiaoYuanPuncher-cloudFunction#2]
{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"6f58fd31-ef41-4714-a8be-2daa76dc0b0c","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 256, in main_handler\n    wzxy = WoZaiXiaoYuanPuncher(config)\n  File \"/var/user/index.py\", line 84, in __init__\n    self.leanCloud_obj = leanCloud(self.leanCloud_data['appId'],self.leanCloud_data['masterKey'])\n  File \"/var/user/index.py\", line 13, in __init__\n    self.obj = leancloud.Query('Info').first()\n  File \"/var/user/leancloud/query.py\", line 213, in first\n    raise LeanCloudError(101, \"Object not found\")\nleancloud.errors.LeanCloudError: LeanCloudError: [101] Object not found","statusCode":430}

**Comment by Chorer** [comment]
https://github.com/Chorer/WoZaiXiaoYuanPuncher-cloudFunction/issues/1
