### ISSUE TITLE
大佬请帮忙看一下哪里出了问题

### ISSUE THREAD

**Issue by jiasheny** [Chorer/WoZaiXiaoYuanPuncher-cloudFunction#3]
{"errorCode":1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 675, in _load\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 655, in _load_unlocked\n  File \"Ϗrozen; importlib._bootstrap_external&gt;\", line 678, in exec_module\n  File \"Ϗrozen; importlib._bootstrap&gt;\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in &lt;module;&gt;\n    import leancloud\nModuleNotFoundError: No module named 'leancloud'","requestId":"fe3556fb-5fc9-4403-bd67-66d056b6eb8b","statusCode":443}

**Comment by Chorer** [comment]
你在 index.py 所在的目录下安装 leanlcoud 了吗？图里这两个是在同一个目录下的：

![image](https://user-images.githubusercontent.com/43442630/131470682-b7b4b66f-a88b-49bb-aebb-70ee0f5a4d16.png)

**Comment by jiasheny** [comment]
![image](https://user-images.githubusercontent.com/62108804/131475786-063fedf5-0a4a-4b2b-be73-5db0156b18cc.png)
是的吧
